# Group Описание с якорем

<!-- anchor: description -->

Демонстрация возможности использования якоря в описании.

## Первый заголовок

<!-- anchor: first-header -->

Заголовок с якорем.

## Второй заголовок

*Заголовок без якоря.*


# Group Группа с якорем

<!-- anchor: my-group -->

Демонстрация возможности использования якоря в ресурсах.

## Ресурс с якорем [/resource-with-anchor]

<!-- anchor: resource -->

### Первый запрос с якорем [GET]

<!-- anchor: first-action -->

+ Response 200 (application/json)

### Второй запрос без якоря [POST]

+ Response 200 (application/json)
