# Group Описание с якорем

<!-- anchor: description -->

[Исходный файл](https://github.com/funbox/blueprinter-frontend/blob/master/src/apib-mock/blocks/anchors.apib)

Демонстрация возможности использования якоря в описании.

## Первый заголовок

<!-- anchor: first-header -->

Заголовок с якорем.

## Второй заголовок

*Заголовок без якоря.*


# Group Группа с якорем

<!-- anchor: my-group -->

[Исходный файл](https://github.com/funbox/blueprinter-frontend/blob/master/src/apib-mock/blocks/anchors.apib#L20)

Демонстрация возможности использования якоря в ресурсах.

## Ресурс с якорем [/resource-with-anchor]

<!-- anchor: resource -->

### Первый запрос с якорем [GET]

<!-- anchor: first-action -->

+ Response 200 (application/json)

### Второй запрос без якоря [POST]

+ Response 200 (application/json)


# Group Группа сущностей с якорем

[Исходный файл](https://github.com/funbox/blueprinter-frontend/blob/master/src/apib-mock/blocks/anchors.apib#L43)

## Message Message c якорем

<!-- anchor: message -->

Демонстрация возможности использования якоря в секции Message.

## SubGroup SubGroup c якорем

<!-- anchor: subgroup -->

Демонстрация возможности использования якоря в SubGroup.

### Message Вложенная секция Message c якорем

<!-- anchor: nested-message -->

Демонстрация возможности использования якоря во вложенной секции Message.
