# Group Body Generation

## Body Generation [GET /body_generation]

+ Response 200 (application/json)
  + Attributes
    + field0: 0 (number, required)
    + One Of
      + option1: 1 (number, required)
      + option2 (object, required)
        + One Of
          + option3: 3 (number, required)
          + option4: 4 (number, required)
    + One Of
      + option5: 5 (number, required)
      + option6: 6 (number, required)
      + option7: 7 (number, required)
