# Data Structures

## SelectObjects

+ One Of
    + Properties - выбрать только указанные сущности
        + ids: `6a5dd3ab-e39f-4f1c-a5d4-79a884b21c14` (array[string], required) - выбрать только указанные сущности
    + Properties - выбрать все сущности, кроме указанных
        + idsExcept: `6a5dd3ab-e39f-4f1c-a5d4-79a884b21c14` (array[string], required) - выбрать все сущности, кроме указанных

## Type (enum)

## MessageType (Type)

+ incoming
+ outcoming

## MessageState(enum[string])

+ `awaiting_report` - Отправлено
+ `ready` - Не отправлено
+ `delivered` - Доставлено
+ `failed` - Не доставлено
+ `unapproved` - Не отправлено

## Tag

+ `id`: `42` (number, required) - идентификатор тега
+ `title`: `some tag` (string, required) - текст тега

## Note

+ `text` (string)

## Message

+ id (object)
    + `type` (MessageType, required)
    + `state` (MessageState, required)
    + `author_id` (number, required) - идентификатор автора сообщения
    + `id`: `1` (string, required) - ID
+ `text`: `Hello world` (string, required) - текст сообщения
+ `tags` (array[Tag], optional) - теги сообщения

## Base Response (object)
+ status: OK (required, fixed) - успешный результат
+ result (optional, object) - объект с данными

## Response A (object)
+ client_id (enum[string], optional)
  + Members
    + web

## Response B (object)
+ timestamp: `1560513461` (number, required)
+ body: `Завтра +5, возможны цунами` (string, required)

## Response C (object)
+ msisdn: 79251112233 (number, required)
+ status: `subscribed` (string, required)


# Group Data Structures

[Исходный файл](https://github.com/funbox/blueprinter/blob/master/src/apib-mock/blocks/data-structures.apib)

Демонстрация создания переиспользуемых структур данных с помощью секции Data Structures и последующего использования этих структур при описании ответов.

## GET /chat

+ Response 200 (application/json)
    + Attributes (array[Message])

+ Response 200 (application/json)
    + Attributes (array)
        + `result` (array[Note])
            + 0
            + 1
            + 2

+ Response 200 (application/json)
    + Attributes (SelectObjects)


## GET /base-and-unique

Демонстрация использования базовой структуры для формирования ответа и переопределения одного из полей этой структуры отдельной структурой

+ Response 200 (application/json)
  Base + Response A
  + Attributes (Base Response)
    + result(Response A)

+ Response 200 (application/json)
  Base + Response B
  + Attributes (Base Response)
    + result(array[Response B])

+ Response 200 (application/json)
  Base + Response C
  + Attributes (Base Response)
    + result(Response C)
