# Group Группа со сложным описанием

[Исходный файл](https://github.com/funbox/blueprinter/blob/master/src/apib-mock/blocks/description.apib)

Текст
можно разделить
на несколько строк

Вложенные списки с примерами отформатированного текста:
* Параметры `ids` и `idsExcept`
  1) Для методов API, в которых доступны параметры `ids` и `idsExcept`, не могут быть переданы исключающий и включающий параметры одновременно.
  2) Параметр `idsExcept` отвечает за выбор всех сущностей, кроме указанных.
     Пример: `employees: {idsExcept: ['uuid']}` приведет к выбору всех сотрудников клиента, кроме сущности с идентификатором `uuid`.
  3) При передаче в параметре `idsExcept` пустого массива будут выбраны все сущности.
     Пример: `employees: {idsExcept: []}` приведет к выбору всех сотрудников клиента.
* Время `unix timestamp`
  * Передается целым числом секунд с 1 января 1970 г. в UTC.
* Параметр `search`
  * Длина строки, указанной в качестве значения для параметра, во всех запросах не должна превышать 255 символов.
* Методы получения сущностей по списку их идентификаторов
  * Правильно по REST было бы использовать для этого запросы `GET /entities?ids[]=UUID1&ids[]=UUID2&...`.
  * У этого решения есть недостаток: большое количество UUID использовать нельзя из-за ограничений на максимальную длину запроса в веб-серверах и клиентах.
  * Решение: *передавать UUID в теле запроса. Следовательно, глагол должен быть POST или PUT.*
  * Для максимального соответствия принципам REST был придуман виртуальный ресурс **"набор сущностей"** (set). Все переданные в запросе UUID составляют один набор.
  * Набор сущностей **"создается"** на сервере запросом `POST /entities/sets`. В ответ на запрос возвращается представление "созданного" набора — массив всех найденных сущностей из набора. Если какие-то сущности найти не удалось, они не возвращаются; ошибки при этом не возникает.
  * На самом деле на сервере ничего не создается и в базе данных ничего не сохраняется.
* Присвоение адресов
  * Адреса присваиваются **асинхронно**!
  * Сразу после создания зоны, объекта, получения новых координат сотрудника их адрес может быть null. Через некоторое время им будет присвоен "нормальный" адрес. Это делается отдельным фоновым процессом.
  * В нормальном режиме работы сервера присвоение адреса занимает 100—200 мс. Если геокодер перегружен, это время может быть больше.
  * Если вы хотите показать адрес зоны или объекта пользователю, а он пока null, обновите модель с сервера, чтобы получить актуальный адрес.

Блок кода:
```
{
  "code": 123,
  "message": "ErrorType",
  "details": "Error detailed message"
}
```

Ссылка:
<a href="https://www.google.com/">
  Нажми на меня
</a>

Картинка:
<img src="https://via.placeholder.com/600/1EBC86/14182F" alt="Wow! This is image." width="600"/>

## Агентства [/agencies]

### Создать агентство [POST]

+ Request (application/json)

    Test request description 1
    Test request description 2
    Test request description 3

    Error structure:
    ```
    {
      "code": 123,
      "message": "ErrorType",
      "details": "Error detailed message"
    }
    ```

    + Attributes
        + name (string)

+ Response 200 (application/json)

    Test response description 1
    Test response description 2
    Test response description 3

    Общее положение:

    * Параметры `ids` и `idsExcept`
      1) Для методов API, в которых доступны параметры `ids` и `idsExcept`, не могут быть переданы исключающий и включающий параметры одновременно.
      2) Параметр `idsExcept` отвечает за выбор всех сущностей, кроме указанных.
         Пример: `employees: {idsExcept: ['uuid']}` приведет к выбору всех сотрудников клиента, кроме сущности с идентификатором `uuid`.
      3) При передаче в параметре `idsExcept` пустого массива будут выбраны все сущности.
         Пример: `employees: {idsExcept: []}` приведет к выбору всех сотрудников клиента.

    + Attributes
        + status: `ok` (required, fixed)

