# Получить ресурсы [GET /resources]

[Исходный файл](https://github.com/funbox/blueprinter/blob/master/src/apib-mock/blocks/resources.apib)

Если группа не определена, ресурсы автоматически будут объединены в группу "Resource Group"

+ Response 200

# Добавить ресурс [POST /resources]

+ Response 200

# Изменить ресурс [PUT /resource]

+ Response 200

# Удалить ресурс [DELETE /resource]

+ Response 200

