# Data Structures

## UnauthorizedError (object)

+ `status` (enum, required)
  + `unauthorized`
  + `internalError`


# Resource Prototypes

## NotFound

+ Response 404 (application/json)
  Прототип NotFound
    + Attributes
        + `status`: `not found` (string, required, fixed)

## AccessDenied

+ Response 200 (application/json)
  Прототип AccessDenied
    + Attributes
        + `status`: `error` (string, required, fixed)
        + `error`: `access_denied` (string, required, fixed) - Доступ запрещен

## UserResource (NotFound)

+ Response 200 (application/json)
  Принадлежит прототипу UserResource
    + Attributes (UnauthorizedError)

+ Response 403 (application/json)
  Принадлежит прототипу UserResource
    + Attributes
        + `status`: `permission denied` (string, required, fixed)


# Group Resource Prototypes для groups (UserResource)

[Исходный файл](https://github.com/funbox/blueprinter/blob/master/src/apib-mock/blocks/resource-prototypes.apib)

Демонстрация создания переиспользуемых ответов с помощью секции Resource Prototypes и последующего использования этих структур при описании ответов.

## Комментарии [/comments]

### GET

+ Response 200 (application/json)
    + Attributes (array)

### POST

+ Request (application/json)
    + Body

          {
            "text": "My comment"
          }

+ Response 204

## Заметки [/notes]

### GET

+ Response 200 (application/json)
    + Attributes (array)

### POST

+ Request (application/json)
    + Body

          {
            "text": "Test note"
          }

+ Response 204


# Group Resource Prototypes для endpoint

[Исходный файл](https://github.com/funbox/blueprinter/blob/master/src/apib-mock/blocks/resource-prototypes.apib#L82)

## Рассылки [GET /campaigns] (NotFound)

+ Response 200 (application/json)
    + Attributes (array)

## Рассылка [GET /campaign] (AccessDenied, NotFound)

+ Response 200 (application/json)
    + Attributes (object)
