# Data Structures

## Profile (object)

+ `name`: `Сантьяго Гомес` (string, required) - Имя пользователя
+ `email`: `someuser@mail.ru` (string, required) - Email
+ `timezone` (Timezone, nullable, required) - Часовой пояс
+ `balance`: `2000` (number, nullable, required) - Баланс пользователя
