# Data Structures

## Timezone (object)

+ `id`: `1` (number, required) - Идентификатор часового пояса
+ `name`: `MSK (UTC+03:00) Москва, Санкт-Петербург (MSK)` (string, required) - Название часового пояса
+ `tz`: `Europe/Moscow` (string, required) - Символьный код часового пояса
